### ISSUE TITLE
Add short description

### ISSUE THREAD

**Issue by andreasgan** [bcc-code/bcc-wp-proxy#1]
Just curious what this is, and how it differs from using a reverse proxy tool

**Comment by rvanoord** [comment]
Hi Andreas,

There are a number of differences:
1. The proxy handles OIDC authentication - this is not supported out of box
in wordpress. In combination with a simple WP plugin, users are
automatically logged in. There are of course plugins that support OIDC in
WordPress, but WordPress isn't designed to run multiple instances, making
scaling hard.
2. User mapping logic allows multiple OIDC users to be linked to the same
WP user (= caching benefits)
3. The proxy makes OIDC access tokens available (e.g. for use by widgets)
4. The proxy selectively caches images and text and is designed to use a
distributed cache (Redis) meaning the proxy can scale horizontally

**Comment by rvanoord** [comment]
Done!
